/* eslint-disable prettier/prettier */
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const CHECK_AUTH = "CHECK_AUTH";

export const GET_USER = "GET_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const REGISTER = "REGISTER";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const BOOKMARKED_POSTS = "BOOKMARKED_POSTS";
export const LIKED_POSTS = "LIKED_POSTS";
export const FOLLOWED_COLLECTIONS = "FOLLOWED_COLLECTIONS";
export const POST_RETRIEVED_USER_COLLECTION_ORIENTED = "POST_RETRIEVED_USER_COLLECTION_ORIENTED";
export const USER_COLLECTIONS = "USER_COLLECTIONS";
export const FOLLOW = "FOLLOW";
export const FOLLOWERS = "FOLLOWERS";
export const FOLLOWING = "FOLLOWING";
export const USER_FOLLOWERS = "USER_FOLLOWERS";
export const USER_FOLLOWING = "USER_FOLLOWING";

export const COLLECTIONS = "COLLECTIONS";
export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const DESTROY_COLLECTION = "DESTROY_COLLECTION";
export const FOLLOW_COLLECTION = "FOLLOW_COLLECTION";

export const POSTS = "POSTS";
export const CREATE_POST = "CREATE_POST";
export const RELATED_POSTS = "RELATED_POSTS,";
export const UPLOAD_FEATURED_IMAGE = "UPLOAD_FEATURED_IMAGE";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const CHANGE_ACCESSIBILITY = "CHANGE_ACCESSIBILITY";
export const UPDATE = "UPDATE";
export const SHOW = "SHOW";
export const BOOKMARK_POST = "BOOKMARK_POST";
export const LIKE_POST = "LIKE_POST";
export const USER_POSTS = "USER_POSTS";
export const POST_RETRIEVE_USER_COLLECTION_ORIENTED = "POST_RETRIEVE_USER_COLLECTION_ORIENTED";
export const POST_RETRIEVE_COLLECTION_ORIENTED = "POST_RETRIEVE_COLLECTION_ORIENTED";